application:
  title: @project.name@
  description: @project.description@
  version: @project.version@

server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      collection: ${SPRING_DATA_MONGODB_COLLECTION}